---
- name: Buildkit | Install buildkit
  ansible.builtin.unarchive:
    # TODO

- name: Buildkit | Copy buildkit service file
  ansible.builtin.copy:
    src:
    dest:
  become: true

- name: Buildkit | Start buildkit service
  ansible.builtin.service:
    name: buildkit.service
    state: started
    enabled: true
    daemon_reload: true
  become: true